sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t fdubuisson/node-red-wiringpi .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=0.16.2
    docker tag fdubuisson/node-red-wiringpi fdubuisson/node-red-wiringpi:$TAG
    docker push fdubuisson/node-red-wiringpi:$TAG
    docker push fdubuisson/node-red-wiringpi
  fi
